using System;
using System.Collections.Generic;
using System.Text;
using CL.WebLogic.Templates.Ast;
using CL.WebLogic.Templates.Parsing;

namespace CL.WebLogic.TemplateCompiler;

/// <summary>
/// Emits a C# render class for a parsed template. The generated code contains
/// the template's structure as real C# (string appends, foreach, if/switch) and
/// delegates ALL value semantics to <c>TemplateRuntime</c> — the same methods
/// the AST interpreter calls — so compiled output is identical by construction.
/// </summary>
internal static class TemplateEmitter
{
    private const string Rt = "global::CL.WebLogic.Theming.TemplateRuntime";
    private const string AstNs = "global::CL.WebLogic.Templates.Ast";

    public static string Emit(string key, string text)
    {
        var doc = TemplateParser.Parse(text);
        var hash = TemplateSourceHash.Compute(text);
        var className = TemplatePathMapper.ToClassName(key);

        var state = new EmitState();
        var body = new CodeWriter(indent: 2);
        body.Line("var sb = ctx.Output;");
        EmitNodes(body, doc.Nodes, state);

        var sections = new CodeWriter(indent: 2);
        foreach (var section in doc.Sections)
        {
            sections.Line("{");
            sections.Indent();
            sections.Line("var __prevOut = ctx.Output;");
            sections.Line("ctx.Output = new global::System.Text.StringBuilder();");
            sections.Line("try");
            sections.Line("{");
            sections.Indent();
            sections.Line("var sb = ctx.Output;");
            EmitNodes(sections, section.Body, state);
            sections.Line($"sections[{Q(section.Name)}] = ctx.Output.ToString();");
            sections.Outdent();
            sections.Line("}");
            sections.Line("finally");
            sections.Line("{");
            sections.Indent();
            sections.Line("ctx.Output = __prevOut;");
            sections.Outdent();
            sections.Line("}");
            sections.Outdent();
            sections.Line("}");
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Compiled by CL.WebLogic.TemplateCompiler from: " + key);
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable 0219, 1998, 8019");
        sb.AppendLine();
        sb.AppendLine("namespace CL.WebLogic.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {className} : global::CL.WebLogic.Theming.ICompiledTemplate");
        sb.AppendLine("{");
        sb.AppendLine($"    public string NormalizedPath => {Q(key)};");
        sb.AppendLine($"    public string SourceHash => {Q(hash)};");
        sb.AppendLine($"    public string? LayoutPath => {(doc.LayoutPath is null ? "null" : Q(doc.LayoutPath))};");
        sb.AppendLine();

        foreach (var field in state.HoistedFields)
            sb.AppendLine("    " + field);
        if (state.HoistedFields.Count > 0)
            sb.AppendLine();

        sb.AppendLine("    public async global::System.Threading.Tasks.Task RenderBodyAsync(global::CL.WebLogic.Theming.WebTemplateContext ctx)");
        sb.AppendLine("    {");
        sb.Append(body);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async global::System.Threading.Tasks.Task RenderSectionsAsync(global::CL.WebLogic.Theming.WebTemplateContext ctx, global::System.Collections.Generic.IDictionary<string, string> sections)");
        sb.AppendLine("    {");
        sb.Append(sections);
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine($"    internal static void __Register() => global::CL.WebLogic.Theming.CompiledTemplateRegistry.Register(new {className}());");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitNodes(CodeWriter w, IReadOnlyList<TemplateNode> nodes, EmitState state)
    {
        foreach (var node in nodes)
        {
            switch (node)
            {
                case LiteralNode literal:
                    if (literal.Text.Length > 0)
                        w.Line($"sb.Append({Q(literal.Text)});");
                    break;

                case VerbatimNode verbatim:
                    if (verbatim.Text.Length > 0)
                        w.Line($"sb.Append({Q(verbatim.Text)});");
                    break;

                case TokenNode token:
                    w.Line($"sb.Append({Rt}.Format({FilteredExpr(token, state)}, {(token.Raw ? "false" : "true")}));");
                    break;

                case LegacyTokenNode legacy:
                    w.Line($"sb.Append({Rt}.LegacyToken(ctx, {Q(legacy.Dotted)}));");
                    break;

                case CsrfNode csrf:
                    w.Line($"sb.Append(ctx.Services.Csrf(ctx, {AstNs}.CsrfKind.{csrf.Kind}));");
                    break;

                case RenderHeadNode:
                    w.Line($"sb.Append({Rt}.RenderHead(ctx));");
                    break;

                case RenderBodyNode:
                    w.Line("sb.Append(ctx.RenderBody ?? string.Empty);");
                    break;

                case RenderSectionNode section:
                    w.Line($"sb.Append({Rt}.Section(ctx, {Q(section.Name)}));");
                    break;

                case WidgetAreaNode area:
                    w.Line($"await ctx.Services.RenderWidgetAreaAsync(ctx, {Q(area.Area)}).ConfigureAwait(false);");
                    break;

                case WidgetNode widget:
                    EmitWidget(w, widget, state);
                    break;

                case PartialNode partial:
                    EmitPartial(w, partial, state);
                    break;

                case ForeachNode loop:
                    EmitForeach(w, loop, state);
                    break;

                case IfNode conditional:
                    EmitIf(w, conditional, state);
                    break;

                case SwitchNode @switch:
                    EmitSwitch(w, @switch, state);
                    break;
            }
        }
    }

    private static void EmitWidget(CodeWriter w, WidgetNode widget, EmitState state)
    {
        var n = state.Next();
        w.Line("{");
        w.Indent();
        w.Line($"var __attrs{n} = new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.OrdinalIgnoreCase);");
        foreach (var attr in widget.Attributes)
            w.Line($"__attrs{n}[{Q(attr.Name)}] = {InlineExpr(attr.Value, state)};");
        w.Line($"await ctx.Services.RenderWidgetAsync(ctx, {Q(widget.Name)}, __attrs{n}).ConfigureAwait(false);");
        w.Outdent();
        w.Line("}");
    }

    private static void EmitPartial(CodeWriter w, PartialNode partial, EmitState state)
    {
        if (partial.Arguments.Count == 0)
        {
            w.Line($"await ctx.Services.RenderPartialAsync(ctx, {Q(partial.Path)}, null).ConfigureAwait(false);");
            return;
        }

        var n = state.Next();
        w.Line("{");
        w.Indent();
        w.Line($"var __args{n} = new global::System.Collections.Generic.Dictionary<string, object?>(global::System.StringComparer.OrdinalIgnoreCase);");
        foreach (var arg in partial.Arguments)
        {
            var valueExpr = arg.IsLiteral ? Q(arg.Literal ?? string.Empty) : ResolveExpr(arg.Selector!);
            w.Line($"__args{n}[{Q(arg.Name)}] = {valueExpr};");
        }
        w.Line($"await ctx.Services.RenderPartialAsync(ctx, {Q(partial.Path)}, __args{n}).ConfigureAwait(false);");
        w.Outdent();
        w.Line("}");
    }

    private static void EmitForeach(CodeWriter w, ForeachNode loop, EmitState state)
    {
        var n = state.Next();
        w.Line("{");
        w.Indent();
        w.Line($"var __items{n} = {Rt}.AsItems({ResolveExpr(loop.Source)});");
        w.Line($"var __prevItem{n} = ctx.CurrentItem;");
        w.Line($"var __prevLoop{n} = ctx.Loop;");
        w.Line($"var __prevAliases{n} = ctx.Aliases;");
        w.Line("try");
        w.Line("{");
        w.Indent();
        w.Line($"for (var __i{n} = 0; __i{n} < __items{n}.Count; __i{n}++)");
        w.Line("{");
        w.Indent();
        w.Line($"ctx.CurrentItem = __items{n}[__i{n}];");
        w.Line($"ctx.Loop = new global::CL.WebLogic.Theming.TemplateLoopState(__i{n}, __items{n}.Count);");
        if (loop.Alias is not null)
            w.Line($"ctx.Aliases = {Rt}.WithAlias(__prevAliases{n}, {Q(loop.Alias)}, __items{n}[__i{n}]);");
        EmitNodes(w, loop.Body, state);
        w.Outdent();
        w.Line("}");
        w.Outdent();
        w.Line("}");
        w.Line("finally");
        w.Line("{");
        w.Indent();
        w.Line($"ctx.CurrentItem = __prevItem{n};");
        w.Line($"ctx.Loop = __prevLoop{n};");
        w.Line($"ctx.Aliases = __prevAliases{n};");
        w.Outdent();
        w.Line("}");
        w.Outdent();
        w.Line("}");
    }

    private static void EmitIf(CodeWriter w, IfNode node, EmitState state)
    {
        for (var i = 0; i < node.Branches.Count; i++)
        {
            w.Line($"{(i == 0 ? "if" : "else if")} ({CondExpr(node.Branches[i].Condition, state)})");
            w.Line("{");
            w.Indent();
            EmitNodes(w, node.Branches[i].Body, state);
            w.Outdent();
            w.Line("}");
        }

        if (node.Else is not null)
        {
            w.Line("else");
            w.Line("{");
            w.Indent();
            EmitNodes(w, node.Else, state);
            w.Outdent();
            w.Line("}");
        }
    }

    private static void EmitSwitch(CodeWriter w, SwitchNode node, EmitState state)
    {
        var n = state.Next();
        w.Line("{");
        w.Indent();
        w.Line($"var __sw{n} = {Rt}.SwitchSubject({ResolveExpr(node.Subject)});");

        for (var i = 0; i < node.Cases.Count; i++)
        {
            w.Line($"{(i == 0 ? "if" : "else if")} (string.Equals(__sw{n}, {Q(node.Cases[i].Value)}, global::System.StringComparison.OrdinalIgnoreCase))");
            w.Line("{");
            w.Indent();
            EmitNodes(w, node.Cases[i].Body, state);
            w.Outdent();
            w.Line("}");
        }

        if (node.Default is not null)
        {
            w.Line(node.Cases.Count > 0 ? "else" : "// default only");
            w.Line("{");
            w.Indent();
            EmitNodes(w, node.Default, state);
            w.Outdent();
            w.Line("}");
        }

        w.Outdent();
        w.Line("}");
    }

    // ── expressions ────────────────────────────────────────────────────────

    private static string ResolveExpr(TemplateSelector selector) =>
        $"await {Rt}.ResolveAsync(ctx, {AstNs}.TemplateScope.{selector.Scope}, {Q(selector.Key)}, {(selector.RawScope is null ? "null" : Q(selector.RawScope))}).ConfigureAwait(false)";

    private static string FilteredExpr(TokenNode token, EmitState state)
    {
        var resolved = ResolveExpr(token.Selector);
        if (token.Filters.Count == 0)
            return resolved;

        var field = state.HoistFilters(token.Filters);
        return $"{Rt}.ApplyFilters({resolved}, {field})";
    }

    private static string InlineExpr(IReadOnlyList<TemplateNode> nodes, EmitState state)
    {
        if (nodes.Count == 0)
            return "\"\"";

        var parts = new List<string>();
        foreach (var node in nodes)
        {
            switch (node)
            {
                case LiteralNode literal:
                    parts.Add(Q(literal.Text));
                    break;
                case TokenNode token:
                    parts.Add($"{Rt}.Format({FilteredExpr(token, state)}, false)");
                    break;
            }
        }

        if (parts.Count == 0)
            return "\"\"";
        if (parts.Count == 1)
            return parts[0];
        return "string.Concat(" + string.Join(", ", parts) + ")";
    }

    private static string CondExpr(TemplateCondition condition, EmitState state)
    {
        switch (condition)
        {
            case NotCondition not:
                return $"!({CondExpr(not.Inner, state)})";
            case AuthCondition:
                return $"{Rt}.IsAuthenticated(ctx)";
            case AccessGroupCondition group:
            {
                var items = new List<string>();
                foreach (var g in group.Groups)
                    items.Add(Q(g));
                return $"{Rt}.HasAnyAccessGroup(ctx, new string[] {{ {string.Join(", ", items)} }})";
            }
            case PermissionCondition permission:
                return $"{Rt}.HasPermission(ctx, {Q(permission.Permission)})";
            case TruthyCondition truthy:
                return $"{Rt}.Truthy({ResolveExpr(truthy.Selector)})";
            case CompareCondition compare:
            {
                var right = compare.Right.IsLiteral
                    ? Q(compare.Right.Literal ?? string.Empty)
                    : ResolveExpr(compare.Right.Selector!);
                return $"{Rt}.Compare({ResolveExpr(compare.Left)}, {AstNs}.CompareOp.{compare.Op}, {right})";
            }
            default:
                return "false";
        }
    }

    /// <summary>C# string literal with full escaping.</summary>
    private static string Q(string value)
    {
        var sb = new StringBuilder(value.Length + 8);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\r': sb.Append("\\r"); break;
                case '\n': sb.Append("\\n"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    if (char.IsControl(c) || c == '\u2028' || c == '\u2029')
                        sb.Append("\\u").Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    else
                        sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private sealed class EmitState
    {
        private int _counter;
        public List<string> HoistedFields { get; } = new();

        public int Next() => _counter++;

        /// <summary>Hoists a filter chain into a static readonly field; returns the field name.</summary>
        public string HoistFilters(IReadOnlyList<TemplateFilter> filters)
        {
            var name = "__filters" + HoistedFields.Count;
            var items = new List<string>();
            foreach (var f in filters)
                items.Add($"({Q(f.Name)}, {(f.Arg is null ? "null" : Q(f.Arg))})");
            HoistedFields.Add(
                $"private static readonly (string Name, string? Arg)[] {name} = new (string, string?)[] {{ {string.Join(", ", items)} }};");
            return name;
        }
    }

    private sealed class CodeWriter
    {
        private readonly StringBuilder _sb = new();
        private int _indent;

        public CodeWriter(int indent) => _indent = indent;

        public void Indent() => _indent++;
        public void Outdent() => _indent--;

        public void Line(string text)
        {
            for (var i = 0; i < _indent; i++)
                _sb.Append("    ");
            _sb.AppendLine(text);
        }

        public override string ToString() => _sb.ToString();
    }
}
